import type { Config } from "./config.js";
import type { HorizonDb } from "./db/client.js";
import type { CatalogAdapter } from "./adapters/woo.js";
import type { StorefrontAdapter } from "./adapters/storefront.js";
import type { MerchantAdapter } from "./adapters/merchant.js";
import type { HealthAdapter } from "./adapters/health.js";
import type { GitAdapter } from "./adapters/git.js";
import type { GithubAdapter } from "./adapters/github.js";
import type { AuditLog } from "./audit/log.js";
import type { JobQueue } from "./jobs/queue.js";
import type { JobRunner } from "./jobs/runner.js";
import type { ResourceServer } from "./auth/resource-server.js";
import type { CommerceAdapter } from "./adapters/commerce.js";
import type { Warehouse } from "./adapters/warehouse.js";
import type { AssistantAdapter } from "./adapters/assistant.js";
import type { SeoReportAdapter } from "./adapters/seo-report.js";
import type { AnalyticsAdapter } from "./adapters/analytics.js";
import type { CompetitorsAdapter } from "./adapters/competitors.js";
import type { InsightsAdapter } from "./adapters/insights.js";
import type Database from "better-sqlite3";

export type AppServices = {
  config: Config;
  db: HorizonDb;
  sqlite: Database.Database;
  auth: ResourceServer;
  catalog: CatalogAdapter;
  woo: CatalogAdapter;
  commerce: CommerceAdapter;
  warehouse: Warehouse;
  assistant: AssistantAdapter;
  seo: SeoReportAdapter;
  analytics: AnalyticsAdapter;
  competitors: CompetitorsAdapter;
  insights: InsightsAdapter;
  storefront: StorefrontAdapter;
  merchant: MerchantAdapter;
  health: HealthAdapter;
  git: GitAdapter;
  github: GithubAdapter;
  audit: AuditLog;
  jobs: JobQueue;
  runner: JobRunner;
  worker: { stop: () => void; tick: () => Promise<void>; lastTickAt: number | null; stopped: boolean };
  startedAt: number;
};
