import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),config=JSON.parse(fs.readFileSync(process.argv[2]||path.join(root,'framework/store.example.json'),'utf8'));
if(!/^[a-z][a-z0-9-]{2,40}$/.test(config.slug))throw new Error('Invalid store');
if(!['127.0.0.1','localhost'].includes(new URL(config.apiUrl).hostname))throw new Error('Smoke test writes only to a local test store');
const dir=path.join(root,'framework/instances',config.slug);
function wp(code){const r=spawnSync('docker',['compose','-f','compose.json','run','--rm','cli','eval',code],{cwd:dir,encoding:'utf8',timeout:120000,windowsHide:true,maxBuffer:2000000});if(r.status!==0)throw new Error(r.stderr.slice(-1000));return r.stdout;}
console.log('Creando producto de prueba en la instancia local.');
const id=Number(wp('$id=wc_get_product_id_by_sku("FRAMEWORK-SMOKE");$p=$id?wc_get_product($id):new WC_Product_Simple();$p->set_name("Producto de prueba reutilizable");$p->set_slug("producto-de-prueba-reutilizable");$p->set_sku("FRAMEWORK-SMOKE");$p->set_regular_price("12345");$p->set_manage_stock(true);$p->set_stock_quantity(7);$p->set_status("publish");$p->save();echo $p->get_id();').trim());
assert.ok(id>0);wp(`$p=wc_get_product(${id});if(!$p->get_image_id()){require_once ABSPATH.'wp-admin/includes/file.php';require_once ABSPATH.'wp-admin/includes/media.php';require_once ABSPATH.'wp-admin/includes/image.php';$tmp=wp_tempnam('fixture.png');file_put_contents($tmp,base64_decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j4mQAAAAASUVORK5CYII='));$image=media_handle_sideload(array('name'=>'framework-fixture.png','tmp_name'=>$tmp),$p->get_id());if(is_wp_error($image))throw new Exception($image->get_error_message());$p->set_image_id($image);$p->save();}hf_framework_rebuild();`);
const routes=['/','/producto/producto-de-prueba-reutilizable/','/coleccion/','/checkout/'];const timing=[];
for(const route of routes){const start=performance.now(),r=await fetch(config.storefrontUrl+route);assert.equal(r.status,200,route);const html=await r.text();timing.push({route,milliseconds:Math.round(performance.now()-start),bytes:Buffer.byteLength(html)});if(route.includes('/producto/')){assert.match(html,/<h1[^>]*>Producto de prueba reutilizable/);assert.ok(html.includes(config.storefrontUrl+'/producto/producto-de-prueba-reutilizable/'));}assert.ok(!html.includes('"name":"Horizon Fit"'),'SEO identity must not leak');}
const sitemap=await(await fetch(config.storefrontUrl+'/sitemap.xml')).text();assert.ok(sitemap.includes(config.storefrontUrl+'/producto/producto-de-prueba-reutilizable/'));assert.ok(!sitemap.includes('horizonfit.com.ar'));
const productsUrl=config.apiUrl+'/wp-content/uploads/horizon-fit-cache/featured-products.json';const response=await fetch(productsUrl,{headers:{Origin:config.storefrontUrl}});assert.equal(response.headers.get('access-control-allow-origin'),config.storefrontUrl);assert.match(response.headers.get('cache-control')||'',/public, max-age=30/);const products=await response.json();assert.ok(products.some(p=>p.id===id||p.id===String(id)));
const denied=await fetch(config.apiUrl+'/wp-json/horizon-framework/v1/cache/rebuild',{method:'POST'});assert.ok([401,403].includes(denied.status));
const cart=await fetch(config.apiUrl+'/wp-json/wc/store/v1/cart',{headers:{Origin:config.storefrontUrl}});assert.equal(cart.status,200);const token=cart.headers.get('cart-token');assert.ok(token,'cart token');
const add=await fetch(config.apiUrl+'/wp-json/wc/store/v1/cart/add-item',{method:'POST',headers:{'Cart-Token':token,'Content-Type':'application/json',Origin:config.storefrontUrl},body:JSON.stringify({id,quantity:1})});assert.ok([200,201].includes(add.status));const cartBody=await add.json();assert.equal(cartBody.items[0].quantity,1);assert.equal(cartBody.totals.currency_code,'ARS');
assert.ok(!JSON.stringify(products).includes('meta_capi_access_token'));
fs.mkdirSync(path.join(root,'reports'),{recursive:true});const report={store:config.name,productId:id,staticRoutes:timing,seo:'body + metadata + sitemap',cache:'public, max-age=30',cart:'add-item OK; no order or payment created',anonymousRebuild:denied.status};fs.writeFileSync(path.join(root,'reports/framework-smoke.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
